## This is the parser for the Excel files

This is the Parser for the Methods in cultural evolution project.

In [22]:
!git clone https://github.com/KachaikinMarko/CultEvoHW
# I created a Git repository to which, normally each member of my group could download their Excel sheet to analyze.

fatal: destination path 'CultEvoHW' already exists and is not an empty directory.

In [23]:
%cd CultEvoHW

/content/CultEvoHW/CultEvoHW/CultEvoHW/CultEvoHW/CultEvoHW/CultEvoHW/CultEvoHW

In [24]:
import pandas as pd

df_M = pd.read_excel("KACHAIKIN_coding_sheets.xlsx",sheet_name=None)

df_H = pd.read_excel('coding_sheets_HG.xlsx',sheet_name=None)

df_D = pd.read_excel('coding_sheets_DM.xlsx',sheet_name=None)

df_O = df_D = pd.read_excel('Coding sheet_Ofelia.xlsx',sheet_name=None)

# I am using pandas, to not parse manually line by line the excel files. the pandas dataframes are working as usual dictionnaries/lists in Python

In [25]:
df_coderM_WiFa = df_M['WiFa']
df_coderH_WiFa = df_H['WiFa']
df_coderD_WiFa = df_D['WiFa']
df_coderO_WiFa = df_D['WiFa']

df_coderM_WiMo = df_M['WiMo']
df_coderH_WiMo = df_H['WiMo']
df_coderD_WiMo = df_D['WiMo']
df_coderO_WiMo = df_D['WiMo']

df_coderM_HuFa = df_M['HuFa']
df_coderH_HuFa = df_H['HuFa']
df_coderD_HuFa = df_D['HuFa']
df_coderO_HuFa = df_D['HuFa']

df_coderM_HuMo = df_M['HuMo']
df_coderH_HuMo = df_H['HuMo']
df_coderD_HuMo = df_D['HuMo']
df_coderO_HuMo = df_D['HuMo']

df_coderM_WiFa

,Source_ID,Coder_ID,WiFa,WiFa_avoided_interactions,WiFa_time_place_var,WiFa_page_number,WiFa_evidence_quotes,Coder remarks
0,Column H on source_database,"Choose yours, it must just be unique",1/0/444/999,"Act, Pres, Phy, Eye, Speak, Name,Other [ ], NA",Past/Within/Weak/NA,NaN,NaN,NaN
1,"Kopytoff, Igor",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
2,"Seligman, C. G. (Charles Gabriel), 1873-1940",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
3,"Webster, David, 1945-1989",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
4,"Benet, Sula, 1903-",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
5,"Aijmer, Göran",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
6,"Emeneau, M. B. (Murray Barnson), 1904-2005",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
7,"Breton, Raymond, 1609-1679",KachaikinM,1,Speak,NaN,NaN,NaN,NaN
8,"Henriksen, Georg",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
9,"Honigmann, John Joseph",KachaikinM,0,NaN,NaN,NaN,NaN,NaN
10,"Latta, Frank Forrest, 1892-",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
11,"Waheenee, 1839?-",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
12,"Goodale, Jane C. (Jane Carter), 1926-",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
13,"Swartz, Marc J.",KachaikinM,444,Other [specify in evidence_quotes ],NaN,NaN,"""A man clearly recognizes that if he fails to ...","It might be codded as 0, but i decided to add ..."
14,"Heinen, H. Dieter",KachaikinM,999,NaN,NaN,NaN,NaN,NaN
15,"Hugh-Jones, Christine, 1943-",KachaikinM,999,NaN,NaN,NaN,NaN,NaN

In [26]:
df_coderM_WiFa_WiFa = df_coderM_WiFa[['Source_ID','WiFa']].copy()
df_coderH_WiFa_WiFa = df_coderH_WiFa[['Source_ID','WiFa']].copy()
df_coderD_WiFa_WiFa= df_coderD_WiFa[['Source_ID','WiFa']].copy()
df_coderO_WiFa_WiFa = df_coderO_WiFa[['Source_ID','WiFa']].copy()

df_coderM_WiMo_WiMo = df_coderM_WiMo[['Source_ID','WiMo']].copy()
df_coderH_WiMo_WiMo = df_coderH_WiMo[['Source_ID','WiMo']].copy()
df_coderD_WiMo_WiMo= df_coderD_WiMo[['Source_ID','WiMo']].copy()
df_coderO_WiMo_WiMo = df_coderO_WiMo[['Source_ID','WiMo']].copy()

df_coderM_HuFa_HuFa = df_coderM_HuFa[['Source_ID','HuFa']].copy()
df_coderH_HuFa_HuFa = df_coderH_HuFa[['Source_ID','HuFa']].copy()
df_coderD_HuFa_HuFa= df_coderD_HuFa[['Source_ID','HuFa']].copy()
df_coderO_HuFa_HuFa= df_coderO_HuFa[['Source_ID','HuFa']].copy()

df_coderM_HuMo_HuMo = df_coderM_HuMo[['Source_ID','HuMo']].copy()
df_coderH_HuMo_HuMo = df_coderH_HuMo[['Source_ID','HuMo']].copy()
df_coderD_HuMo_HuMo= df_coderD_HuMo[['Source_ID','HuMo']].copy()
df_coderO_HuMo_HuMo = df_coderO_HuMo[['Source_ID','HuMo']].copy()

df_coderM_WiFa_WiFa

                                       Source_ID         WiFa
0                    Column H on source_database  1/0/444/999
1                                 Kopytoff, Igor          999
2   Seligman, C. G. (Charles Gabriel), 1873-1940          999
3                      Webster, David, 1945-1989          999
4                             Benet, Sula, 1903-          999
5                                 Aijmer, Göran          999
6     Emeneau, M. B. (Murray Barnson), 1904-2005          999
7                     Breton, Raymond, 1609-1679            1
8                               Henriksen, Georg          999
9                         Honigmann, John Joseph            0
10                   Latta, Frank Forrest, 1892-          999
11                              Waheenee, 1839?-          999
12         Goodale, Jane C. (Jane Carter), 1926-          999
13                               Swartz, Marc J.          444
14                             Heinen, H. Dieter          999
15                  Hugh-Jones, Christine, 1943-          999

In [27]:
df_coderM_WiFa_avoided_interactions = df_coderM_WiFa[['Source_ID','WiFa_avoided_interactions']].copy()
df_coderH_WiFa_avoided_interactions = df_coderH_WiFa[['Source_ID','WiFa_avoided_interactions']].copy()
df_coderD_WiFa_avoided_interactions= df_coderD_WiFa[['Source_ID','WiFa_avoided_interactions']].copy()
df_coderO_WiFa_avoided_interactions = df_coderO_WiFa[['Source_ID','WiFa_avoided_interactions']].copy()

df_coderM_WiMo_avoided_interactions = df_coderM_WiMo[['Source_ID','WiMo_avoided_interactions']].copy()
df_coderH_WiMo_avoided_interactions = df_coderH_WiMo[['Source_ID','WiMo_avoided_interactions']].copy()
df_coderD_WiMo_avoided_interactions= df_coderD_WiMo[['Source_ID','WiMo_avoided_interactions']].copy()
df_coderO_WiMo_avoided_interactions = df_coderO_WiMo[['Source_ID','WiMo_avoided_interactions']].copy()

df_coderM_HuFa_avoided_interactions = df_coderM_HuFa[['Source_ID','HuFa_avoided_interactions']].copy()
df_coderH_HuFa_avoided_interactions = df_coderH_HuFa[['Source_ID','HuFa_avoided_interactions']].copy()
df_coderD_HuFa_avoided_interactions= df_coderD_HuFa[['Source_ID','HuFa_avoided_interactions']].copy()
df_coderO_HuFa_avoided_interactions= df_coderO_HuFa[['Source_ID','HuFa_avoided_interactions']].copy()

df_coderM_HuMo_avoided_interactions = df_coderM_HuMo[['Source_ID','HuMo_avoided_interactions']].copy()
df_coderH_HuMo_avoided_interactions = df_coderH_HuMo[['Source_ID','HuMo_avoided_interactions']].copy()
df_coderD_HuMo_avoided_interactions= df_coderD_HuMo[['Source_ID','HuMo_avoided_interactions']].copy()
df_coderO_HuMo_avoided_interactions = df_coderO_HuMo[['Source_ID','HuMo_avoided_interactions']].copy()

df_coderM_WiFa_avoided_interactions

,Source_ID,WiFa_avoided_interactions
0,Column H on source_database,"Act, Pres, Phy, Eye, Speak, Name,Other [ ], NA"
1,"Kopytoff, Igor",NaN
2,"Seligman, C. G. (Charles Gabriel), 1873-1940",NaN
3,"Webster, David, 1945-1989",NaN
4,"Benet, Sula, 1903-",NaN
5,"Aijmer, Göran",NaN
6,"Emeneau, M. B. (Murray Barnson), 1904-2005",NaN
7,"Breton, Raymond, 1609-1679",Speak
8,"Henriksen, Georg",NaN
9,"Honigmann, John Joseph",NaN
10,"Latta, Frank Forrest, 1892-",NaN
11,"Waheenee, 1839?-",NaN
12,"Goodale, Jane C. (Jane Carter), 1926-",NaN
13,"Swartz, Marc J.",Other [specify in evidence_quotes ]
14,"Heinen, H. Dieter",NaN
15,"Hugh-Jones, Christine, 1943-",NaN

In [28]:
df_coderM_WiFa_time_place_var = df_coderM_WiFa[['Source_ID','WiFa_time_place_var']].copy()
df_coderH_WiFa_time_place_var = df_coderH_WiFa[['Source_ID','WiFa_time_place_var']].copy()
df_coderD_WiFa_time_place_var = df_coderD_WiFa[['Source_ID','WiFa_time_place_var']].copy()
df_coderO_WiFa_time_place_var = df_coderO_WiFa[['Source_ID','WiFa_time_place_var']].copy()

df_coderM_WiMo_time_place_var = df_coderM_WiMo[['Source_ID','WiMo_time_place_var']].copy()
df_coderH_WiMo_time_place_var = df_coderH_WiMo[['Source_ID','WiMo_time_place_var']].copy()
df_coderD_WiMo_time_place_var = df_coderD_WiMo[['Source_ID','WiMo_time_place_var']].copy()
df_coderO_WiMo_time_place_var = df_coderO_WiMo[['Source_ID','WiMo_time_place_var']].copy()

df_coderM_HuFa_time_place_var = df_coderM_HuFa[['Source_ID','HuFa_time_place_var']].copy()
df_coderH_HuFa_time_place_var = df_coderH_HuFa[['Source_ID','HuFa_time_place_var']].copy()
df_coderD_HuFa_time_place_var = df_coderD_HuFa[['Source_ID','HuFa_time_place_var']].copy()
df_coderO_HuFa_time_place_var = df_coderO_HuFa[['Source_ID','HuFa_time_place_var']].copy()

df_coderM_HuMo_time_place_var = df_coderM_HuMo[['Source_ID','HuMo_time_place_var']].copy()
df_coderH_HuMo_time_place_var = df_coderH_HuMo[['Source_ID','HuMo_time_place_var']].copy()
df_coderD_HuMo_time_place_var = df_coderD_HuMo[['Source_ID','HuMo_time_place_var']].copy()
df_coderO_HuMo_time_place_var = df_coderO_HuMo[['Source_ID','HuMo_time_place_var']].copy()

df_coderM_WiMo_time_place_var

                                       Source_ID  WiMo_time_place_var
0                    Column H on source_database  Past/Within/Weak/NA
1                                 Kopytoff, Igor                  NaN
2   Seligman, C. G. (Charles Gabriel), 1873-1940                  NaN
3                      Webster, David, 1945-1989                  NaN
4                             Benet, Sula, 1903-                  NaN
5                                 Aijmer, Göran                  NaN
6     Emeneau, M. B. (Murray Barnson), 1904-2005                 Past
7                     Breton, Raymond, 1609-1679                  NaN
8                               Henriksen, Georg                  NaN
9                         Honigmann, John Joseph                  NaN
10                   Latta, Frank Forrest, 1892-                  NaN
11                              Waheenee, 1839?-                  NaN
12         Goodale, Jane C. (Jane Carter), 1926-                  NaN
13                               Swartz, Marc J.                  NaN
14                             Heinen, H. Dieter                  NaN
15                  Hugh-Jones, Christine, 1943-                  NaN

In [29]:
# This function takes the source ids from the different codders sheets, and then creates a unique set that contains all coded ressources by an ID
# Expected format of the input is the list of the pages of the sheets, where each sheet is the sheet WiFa,WiMo,HuFa,HuMo of each coder
def IC_Sources_Set(frames):
  B = set()
  for frame in frames:
    # Clean 'Source_ID' values: convert to string, strip whitespace, normalize, and filter out 'nan' strings
    #Caution: This is what a Gemini proposed, as in my code without cleaning, as every member of the groups used different type of sheets documents
    # there was the error with creating different source ids..
    cleaned_source_ids = frame['Source_ID'].astype(str).str.lower().str.replace(r'\s+', ' ', regex=True).str.strip()
    cleaned_source_ids = cleaned_source_ids[cleaned_source_ids != 'nan']
    S = set(cleaned_source_ids.values)
    B = B.union(S)
  # Only remove 'column h on source_database' (after cleaning) if it exists in the set
  if 'column h on source_database' in B:
    B.remove('column h on source_database')
  return B
# print(IC_Sources_Set([df_coderM_WiFa]))

In [30]:

# This function takes an individual codder sheet and the mutual of all codders sources list,
# And creates a new sheet that would containt all the sources and add the values None If the ressource was not codded by a codder
#sources_list is expected to be a set of sources as in an output from IC_Sources_Set

def IC_IndSheet(frame,sources_list):
  # Create a copy to avoid SettingWithCopyWarning
  frame_copy = frame.copy()
  # Clean 'Source_ID' column to ensure uniqueness and consistency
  frame_copy['Source_ID'] = frame_copy['Source_ID'].astype(str).str.lower().str.replace(r'\s+', ' ', regex=True).str.strip()
  # Filter out rows where 'Source_ID' became 'nan' string (from actual NaNs)
  frame_cleaned = frame_copy[frame_copy['Source_ID'] != 'nan']

  # Now drop duplicates based on the cleaned 'Source_ID' and set it as index
  frame_unique_sources = frame_cleaned.drop_duplicates(subset=['Source_ID']).set_index('Source_ID')

  result = (
    frame_unique_sources
      .reindex(sources_list)
      .reset_index()
)
  return result

In [31]:
#This function take the frames from the different coders, and append them one by one


def IC_Sheet(frames,variable_name):
  sources_list = IC_Sources_Set(frames)
  new_frames=[]
  for frame in frames:
    new_frames.append(IC_IndSheet(frame,sources_list))
  new_frames = [
    df.set_index('Source_ID').rename(columns={variable_name: f"Coder_{i+1}"})
    for i, df in enumerate(new_frames)
]

  merged = pd.concat(new_frames, axis=1).reset_index()
  return merged

sources_list = IC_Sources_Set([df_coderM_WiFa,df_coderH_WiFa,df_coderD_HuFa,df_coderO_HuFa])
sources_list

{'aijmer, göran',
 'bastian, misty l.',
 'beierle, john',
 'benet, sula, 1903-',
 'breton, raymond, 1609-1679',
 "buffalo bird woman's garden: agriculture of the hidatsa indians",
 'douglas, williams a.',
 'douglass, william a.',
 'emeneau, m. b. (murray barnson), 1904-2005',
 'goodale, jane c. (jane carter), 1926-',
 'heinen, h. dieter',
 'henriksen, georg',
 'honigmann, john joseph',
 'hugh-jones, christine, 1943-',
 'junod, henri alexandre, 1863-1934',
 'kopytoff, igor',
 'kroeber, a. l. (alfred louis), 1876-1960',
 'latta, frank forrest, 1892-',
 'leenhardt, maurice, 1878-1954',
 'seligman, c. g. (charles gabriel), 1873-1940',
 'swartz, marc j.',
 'waheenee, 1839?-',
 'webster, david, 1945-1989'}

In [32]:

# Here we create all posible 12 InterCoder tables

IC_sheet_WiFa_WiFa = IC_Sheet([df_coderM_WiFa_WiFa,df_coderH_WiFa_WiFa,df_coderD_WiFa_WiFa,df_coderO_WiFa_WiFa], 'WiFa')
IC_sheet_WiMo_WiMo = IC_Sheet([df_coderM_WiMo_WiMo,df_coderH_WiMo_WiMo,df_coderD_WiMo_WiMo,df_coderO_WiMo_WiMo], 'WiMo')
IC_sheet_HuFa_HuFa = IC_Sheet([df_coderM_HuFa_HuFa,df_coderH_HuFa_HuFa ,df_coderD_HuFa_HuFa,df_coderO_HuFa_HuFa], 'HuFa')
IC_sheet_HuMo_HuMo = IC_Sheet([df_coderM_HuMo_HuMo,df_coderH_HuMo_HuMo,df_coderD_HuMo_HuMo,df_coderO_HuMo_HuMo], 'HuMo')



IC_sheet_WiFa_avoided_interactions = IC_Sheet([df_coderM_WiFa_avoided_interactions,df_coderH_WiFa_avoided_interactions,df_coderD_WiFa_avoided_interactions,df_coderO_WiFa_avoided_interactions], 'WiFa_avoided_interactions')
IC_sheet_WiMo_avoided_interactions = IC_Sheet([df_coderM_WiMo_avoided_interactions,df_coderH_WiMo_avoided_interactions,df_coderD_WiMo_avoided_interactions,df_coderO_WiMo_avoided_interactions], 'WiMo_avoided_interactions')
IC_sheet_HuFa_avoided_interactions = IC_Sheet([df_coderM_HuFa_avoided_interactions,df_coderH_HuFa_avoided_interactions ,df_coderD_HuFa_avoided_interactions,df_coderO_HuFa_avoided_interactions], 'HuFa_avoided_interactions')
IC_sheet_HuMo_avoided_interactions = IC_Sheet([df_coderM_HuMo_avoided_interactions,df_coderH_HuMo_avoided_interactions,df_coderD_HuMo_avoided_interactions,df_coderO_HuMo_avoided_interactions], 'HuMo_avoided_interactions')




IC_sheet_WiFa_time_place_var = IC_Sheet(
    [df_coderM_WiFa_time_place_var,
     df_coderH_WiFa_time_place_var,
     df_coderD_WiFa_time_place_var,
     df_coderO_WiFa_time_place_var],
    'WiFa_time_place_var'
)

IC_sheet_WiMo_time_place_var = IC_Sheet(
    [df_coderM_WiMo_time_place_var,
     df_coderH_WiMo_time_place_var,
     df_coderD_WiMo_time_place_var,
     df_coderO_WiMo_time_place_var],
    'WiMo_time_place_var'
)

IC_sheet_HuFa_time_place_var = IC_Sheet(
    [df_coderM_HuFa_time_place_var,
     df_coderH_HuFa_time_place_var,
     df_coderD_HuFa_time_place_var,
     df_coderO_HuFa_time_place_var],
    'HuFa_time_place_var'
)

IC_sheet_HuMo_time_place_var = IC_Sheet(
    [df_coderM_HuMo_time_place_var,
     df_coderH_HuMo_time_place_var,
     df_coderD_HuMo_time_place_var,
     df_coderO_HuMo_time_place_var],
    'HuMo_time_place_var'
)

IC_sheet_HuFa_avoided_interactions

,Source_ID,Coder_1,Coder_2,Coder_3,Coder_4
0,"seligman, c. g. (charles gabriel), 1873-1940",NaN,NaN,Other [specify in evidence_quotes ],Other [specify in evidence_quotes ]
1,"kopytoff, igor",NaN,NaN,NaN,NaN
2,"swartz, marc j.",NaN,NaN,NaN,NaN
3,"douglas, williams a.",NaN,NaN,NaN,NaN
4,buffalo bird woman's garden: agriculture of th...,NaN,NaN,NaN,NaN
5,"waheenee, 1839?-",NaN,NaN,NaN,NaN
6,"leenhardt, maurice, 1878-1954",NaN,NaN,NaN,NaN
7,"bastian, misty l.",NaN,NaN,NaN,NaN
8,"breton, raymond, 1609-1679",NaN,NaN,NaN,NaN
9,"heinen, h. dieter",NaN,NaN,NaN,NaN
10,"benet, sula, 1903-",Speak,"Speak, Name",NaN,NaN
11,"emeneau, m. b. (murray barnson), 1904-2005","Act, Pres, Phy, Eye",Phys,NaN,NaN
12,"webster, david, 1945-1989",NaN,NaN,NaN,NaN
13,"beierle, john",NaN,NaN,NaN,NaN
14,"aijmer, göran",NaN,NaN,NaN,NaN
15,"douglass, william a.",NaN,NaN,NaN,NaN
16,"goodale, jane c. (jane carter), 1926-",NaN,NaN,NaN,NaN
17,"hugh-jones, christine, 1943-",NaN,NaN,NaN,NaN
18,"henriksen, georg",NaN,NaN,NaN,NaN
19,"kroeber, a. l. (alfred louis), 1876-1960",NaN,NaN,NaN,NaN
20,"honigmann, john joseph",NaN,NaN,NaN,NaN
21,"junod, henri alexandre, 1863-1934",NaN,NaN,NaN,NaN
22,"latta, frank forrest, 1892-",NaN,NaN,NaN,NaN

In [33]:

# Here all posible 12 InterCoder tables are rewritten to be numpy arrays

IC_sheet_WiFa_WiFa = IC_sheet_WiFa_WiFa[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()
IC_sheet_WiMo_WiMo = IC_sheet_WiMo_WiMo[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()
IC_sheet_HuFa_HuFa = IC_sheet_HuFa_HuFa[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()
IC_sheet_HuMo_HuMo = IC_sheet_HuMo_HuMo[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()

IC_sheet_WiFa_WiFa = IC_sheet_WiFa_WiFa.astype(float)
IC_sheet_WiMo_WiMo = IC_sheet_WiMo_WiMo.astype(float)
IC_sheet_HuFa_HuFa = IC_sheet_HuFa_HuFa.astype(float)
IC_sheet_HuMo_HuMo = IC_sheet_HuMo_HuMo.astype(float)

IC_sheet_WiFa_avoided_interactions = IC_sheet_WiFa_avoided_interactions[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()
IC_sheet_WiMo_avoided_interactions = IC_sheet_WiMo_avoided_interactions[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()
IC_sheet_HuFa_avoided_interactions = IC_sheet_HuFa_avoided_interactions[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()
IC_sheet_HuMo_avoided_interactions = IC_sheet_HuMo_avoided_interactions[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()




IC_sheet_WiFa_time_place_var = IC_sheet_WiFa_time_place_var[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()

IC_sheet_WiMo_time_place_var = IC_sheet_WiMo_time_place_var[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()

IC_sheet_HuFa_time_place_var = IC_sheet_HuFa_time_place_var[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()

IC_sheet_HuMo_time_place_var = IC_sheet_HuMo_time_place_var[['Coder_1','Coder_2','Coder_3','Coder_4']].to_numpy()

In [61]:
import numpy as np

def transform_value(x):
    # 1. Handle NaN (covers np.nan and float nan)
    if isinstance(x, float) and np.isnan(x):
        return np.nan

    # 2. Handle numbers (int, float but not nan)
    if isinstance(x, (int, float)):
        return float(x)

    # 3. Handle strings
    if isinstance(x, str):
        x = x.strip()

        # Special replacement
        if x == "Other [specify in evidence_quotes ]":
            return "Other"

        # Split comma-separated values
        if "," in x:
            return {item.strip() for item in x.split(",") if item.strip()}

        return {x}

    # Fallback (just return as is)
    return x


def transform_array(arr):
    vectorized = np.vectorize(transform_value, otypes=[object])
    return vectorized(arr).T

In [66]:
IC_sheet_WiFa_WiFa = transform_array(IC_sheet_WiFa_WiFa)
IC_sheet_WiMo_WiMo = transform_array(IC_sheet_WiMo_WiMo)
IC_sheet_HuFa_HuFa = transform_array(IC_sheet_HuFa_HuFa)
IC_sheet_HuMo_HuMo = transform_array(IC_sheet_HuMo_HuMo)

IC_sheet_WiFa_avoided_interactions = transform_array(IC_sheet_WiFa_avoided_interactions)
IC_sheet_WiMo_avoided_interactions = transform_array(IC_sheet_WiMo_avoided_interactions )
IC_sheet_HuFa_avoided_interactions = transform_array(IC_sheet_HuFa_avoided_interactions)
IC_sheet_HuMo_avoided_interactions = transform_array(IC_sheet_HuMo_avoided_interactions)




IC_sheet_WiFa_time_place_var = transform_array(IC_sheet_WiFa_time_place_var)

IC_sheet_WiMo_time_place_var = transform_array(IC_sheet_WiMo_time_place_var)
IC_sheet_HuFa_time_place_var = transform_array(IC_sheet_HuFa_time_place_var)

IC_sheet_HuMo_time_place_var = transform_array(IC_sheet_HuMo_time_place_var)

In [78]:
IC_sheet_HuFa_avoided_interactions

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, {'Speak'},
        {'Eye', 'Act', 'Pres', 'Phy'}, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        {'Speak', 'Name'}, {'Phys'}, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan],
       ['Other', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       ['Other', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
      dtype=object)

## This is the calculation of the ICA metric

In [63]:
import numpy as np
from collections import Counter
import math

def krippendorff_alpha_nominal(data):
    """
    data: 2D numpy array (coders x items)
          entries can be any hashable category or np.nan
    """

    data = np.array(data, dtype=object)

    # Get all valid categories
    categories = set()
    for val in data.flatten():
        if val is not None and not (isinstance(val, float) and np.isnan(val)):
            categories.add(val)

    categories = list(categories)

    # Coincidence matrix
    coincidence = {c: Counter() for c in categories}

    for col in range(data.shape[1]):
        values = [v for v in data[:, col]
                  if v is not None and not (isinstance(v, float) and np.isnan(v))]

        n = len(values)
        if n < 2:
            continue

        for i in range(n):
            for j in range(n):
                if i != j:
                    coincidence[values[i]][values[j]] += 1

    # Observed disagreement Do
    Do = 0
    total_pairs = 0

    for c in categories:
        for k in categories:
            if c != k:
                Do += coincidence[c][k]
            total_pairs += coincidence[c][k]

    if total_pairs == 0:
        return np.nan

    Do = Do / total_pairs

    # Expected disagreement De
    marginals = Counter()
    for c in categories:
        marginals[c] = sum(coincidence[c].values())

    total = sum(marginals.values())

    De = 0
    for c in categories:
        for k in categories:
            if c != k:
                De += marginals[c] * marginals[k]

    De = De / (total * (total - 1)) if total > 1 else 0

    if De == 0:
        return 1.0

    return 1 - (Do / De)

In [72]:
def normalize_multilabel(data):
    out = np.empty_like(data, dtype=object)

    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            val = data[i, j]

            if isinstance(val, set):
                out[i, j] = tuple(sorted(val))  # hashable
            else:
                out[i, j] = val

    return out

krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_WiFa_avoided_interactions))

0.0

In [74]:

alpha_WiFa = krippendorff_alpha_nominal(IC_sheet_WiFa_WiFa)
alpha_WiMo = krippendorff_alpha_nominal(IC_sheet_WiMo_WiMo)
alpha_HuFa = krippendorff_alpha_nominal(IC_sheet_HuFa_HuFa)
alpha_HuMo= krippendorff_alpha_nominal(IC_sheet_HuMo_HuMo)


print("Krippendorff's alpha for the InterCoder Agreement in Presence/Abscence of Avoidance in WiFa:", alpha_WiFa)
print("Krippendorff's alpha for the InterCoder Agreement in Presence/Abscence of Avoidance  in WiMo:", alpha_WiMo)
print("Krippendorff's alpha for the  InterCoder Agreement in Presence/Abscence of Avoidance  in HuFa:", alpha_HuFa)
print("Krippendorff's alpha for the InterCoder Agreement in Presence/Abscence of Avoidance in HuMo:", alpha_HuMo)

Krippendorff's alpha for the InterCoder Presence/Abscence in WiFa: 0.6930067167127618
Krippendorff's alpha for the InterCoder Presence/Abscence  in WiMo: 0.657671381936888
Krippendorff's alpha for the  InterCoder Presence/Abscence  in HuFa: 0.4653349001175089
Krippendorff's alpha for the InterCoder Presence/Abscence in HuMo: 0.5813106796116505

In [77]:

alpha_WiFa_avoided = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_WiFa_avoided_interactions))
alpha_WiMo_avoided = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_WiMo_avoided_interactions))
alpha_HuFa_avoided = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_HuFa_avoided_interactions))
alpha_HuMo_avoided = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_HuMo_avoided_interactions))


print("Krippendorff's alpha for the InterCoder Agreement in WiFa_avoided_interaction:", alpha_WiFa_avoided)
print("Krippendorff's alpha for the InterCoder Agreement  in WiMo_avoided_interaction:", alpha_WiMo_avoided)
print("Krippendorff's alpha for the  InterCoder Agreement  in HuFa_avoided_interaction:", alpha_HuFa_avoided)
print("Krippendorff's alpha for the InterCoder Agreement in HuMo_avoided_interaction:", alpha_HuMo_avoided)

Krippendorff's alpha for the InterCoder Agreement in WiFa_avoided_interaction: 0.0
Krippendorff's alpha for the InterCoder Agreement  in WiMo_avoided_interaction: 0.36585365853658547
Krippendorff's alpha for the  InterCoder Agreement  in HuFa_avoided_interaction: 0.2857142857142858
Krippendorff's alpha for the InterCoder Agreement in HuMo_avoided_interaction: 1.0

In [79]:
alpha_WiFa_time_place_var  = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_WiFa_time_place_var))
alpha_WiMo_time_place_var  = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_WiMo_time_place_var))
alpha_HuFa_time_place_var  = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_HuFa_time_place_var))
alpha_HuMo_time_place_var  = krippendorff_alpha_nominal(normalize_multilabel(IC_sheet_HuMo_time_place_var))


print("Krippendorff's alpha for the InterCoder Agreement in WiFa_time_place_var :", alpha_WiFa_time_place_var)
print("Krippendorff's alpha for the InterCoder Agreement  in WiMo_avoided__time_place_var :", alpha_WiMo_time_place_var)
print("Krippendorff's alpha for the  InterCoder Agreement  in HuFa_avoided__time_place_var :", alpha_HuFa_time_place_var)
print("Krippendorff's alpha for the InterCoder Agreement in HuMo_avoided__time_place_var :", alpha_HuMo_time_place_var)

Krippendorff's alpha for the InterCoder Agreement in WiFa_time_place_var : nan
Krippendorff's alpha for the InterCoder Agreement  in WiMo_avoided__time_place_var : 1.0
Krippendorff's alpha for the  InterCoder Agreement  in HuFa_avoided__time_place_var : 1.0
Krippendorff's alpha for the InterCoder Agreement in HuMo_avoided__time_place_var : nan